#This is a basic workflow for serviapp
name: CI-CD

# Controls when the action will run. 
on: [push] #to any branch
  # Triggers the workflow on push or pull request events but only for the Develop branch
  #push:
  #  branches: [ Develop ]
  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  # This workflow contains multiple jobs

  deploy_to_dev:
      # The type of runner that the job will run on

      runs-on: ubuntu-latest
#      defaults:
#        run:
#          shell: bash -ileo pipefail {0} 
#Deploy dev      
      if: github.ref == 'refs/heads/Develop' # run this job only for the dev branch
      steps:
#        - name: checkout repo#
#          uses: actions/checkout@v2
#
#        - name: Set up QEMU
#          uses: docker/setup-qemu-action@v1
#      
#        - name: Set up Docker Buildx
#          uses: docker/setup-buildx-action@v1
#
#        - name: Login to DockerHub
#          uses: docker/login-action@v1
#          with:
#            username: ${{ secrets.DOCKERHUB_USERNAME }}
#            password: ${{ secrets.DOCKERHUB_TOKEN }}
#      
#        - name: Build and push Back
#          uses: docker/build-push-action@v2
#          with:
#            context: ./Back
#            file: ./Back/Dockerfile
#            push: true
#            tags: ${{ secrets.DOCKERHUB_USERNAME }}/serviapp:back-${{ github.ref_name }}
        - name: checkout repo
          uses: actions/checkout@v2
          
        - name: set env
          env:
            VITE_BASE_URL: 'https://dev.serviapp.solutions:3001'
          run: echo "${{ secrets.ENV_DEV }}" > ./Front/.env

        - name: Use Node.js 16 LTS
          uses: actions/setup-node@v2
          with:
            node-version: '16'
      
        - name: Install NPM Modules
          working-directory: ./Front
          run: npm install

        - name: Build Project
          working-directory: ./Front
          run: CI= npm run build
          
        - name: Create SSH key
          run: |
              install -m 600 -D /dev/null ~/.ssh/id_rsa
              echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
              ssh-keyscan serviapp.solutions > ~/.ssh/known_hosts
        #Back          
        - name: Deploy Back
          run: |
              rsync -ra --delete Back/ ubuntu@serviapp.solutions:/home/ubuntu/serviapp/dev/c16-28-n-node-react/Back/
              ssh -f ubuntu@${{ secrets.SSH_HOST }} /home/ubuntu/serviapp/dev/dev.sh
        #Front
        - name: Deploy Front
          run: |
              echo "${{ secrets.OPT_SRV }}" > Front/dist/.htaccess
              rsync -ra --delete Front/dist/ ubuntu@serviapp.solutions:/var/www/dev.serviapp.solutions/public_html/

#deploy QA

  deploy_to_qa:
      # The type of runner that the job will run on

      runs-on: ubuntu-latest    
      if: github.ref == 'refs/heads/qa' # run this job only for the qa branch

      steps:
        #deploy frontend
        - name: checkout repo
          uses: actions/checkout@v2
          
        - name: set env
          env:
            VITE_BASE_URL: 'https://qa.serviapp.solutions:4001'

        - name: Use Node.js 16 LTS
          uses: actions/setup-node@v2
          with:
            node-version: '16'
      
        - name: Install NPM Modules
          working-directory: ./Front
          run: npm install

        - name: Build Project
          working-directory: ./Front
          run: CI= npm run build
          
        - name: Create SSH key
          run: |
              install -m 600 -D /dev/null ~/.ssh/id_rsa
              echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
              ssh-keyscan serviapp.solutions > ~/.ssh/known_hosts                 
        #Back          
        - name: Deploy Back
          run: |
              rsync -ra --delete Back/ ubuntu@serviapp.solutions:/home/ubuntu/serviapp/qa/c16-28-n-node-react/Back/
              ssh -f ubuntu@${{ secrets.SSH_HOST }} /home/ubuntu/serviapp/qa/qa.sh
        #Front
        - name: Deploy Front
          run: |
              echo "${{ secrets.OPT_SRV }}" > Front/dist/.htaccess
              rsync -ra --delete Front/dist/ ubuntu@serviapp.solutions:/var/www/qa.serviapp.solutions/public_html/

#deploy PROD

  deploy_to_prod:
      # The type of runner that the job will run on

      runs-on: ubuntu-latest    
      if: github.ref == 'refs/heads/main' # run this job only for the main branch

      steps:
        #deploy frontend
        - name: checkout repo
          uses: actions/checkout@v2
          
        - name: set env
          env:
            VITE_BASE_URL: 'https://serviapp.solutions:5001'

        - name: Use Node.js 16 LTS
          uses: actions/setup-node@v2
          with:
            node-version: '16'
      
        - name: Install NPM Modules
          working-directory: ./Front
          run: npm install

        - name: Build Project
          working-directory: ./Front
          run: CI= npm run build
          
        - name: Create SSH key
          run: |
              install -m 600 -D /dev/null ~/.ssh/id_rsa
              echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
              ssh-keyscan serviapp.solutions > ~/.ssh/known_hosts                 
        #Back          
        - name: Deploy Back
          run: |
              rsync -ra --delete Back/ ubuntu@serviapp.solutions:/home/ubuntu/serviapp/prod/c16-28-n-node-react/Back/
              ssh -f ubuntu@${{ secrets.SSH_HOST }} /home/ubuntu/serviapp/prod/prod.sh
        #Front
        - name: Deploy with rsync
          run: |
              echo "${{ secrets.OPT_SRV }}" > Front/dist/.htaccess
              rsync -ra --delete Front/dist/ ubuntu@serviapp.solutions:/var/www/production.serviapp.solutions/public_html/

